### ISSUE TITLE
Paste problems with German keyboard layout

### ISSUE THREAD

**Issue by ChibangLW** [TechxArtisanStudio/Openterface_MacOS#32]
I have two issues with the paste-to-target functionality in the mac app. 

1. `cmd+v` while window is in focus does not paste to target. It translates to `Windows+v` on the windows target. It is a bit confusing because in the menu bar the shortcut is mentioned beside the paste function. 

2. The keyboard layout for paste function is different than host machine physical keyboard layout. 
2.1. German host layout (qwertz): copy letter `z`
2.2. German target layout (qwertz): use paste function -> `y` is pasted. 
2.3. Pressing `z` on host results in `z` inserted on target.

**Comment by ling3ye** [comment]
Hi，[ChibangLW](https://github.com/ChibangLW)

Thank you so much for your valuable feedback.   We truly appreciate you taking the time to share the issues you've encountered with the paste-to-target functionality.

We understand the confusion regarding the cmd+v shortcut and the difference in keyboard layouts between the host and target.   We are actively looking into these issues.

To investigate and resolve the problem, we will be purchasing a German-style keyboard for further testing, as this will help us better replicate and address the behavior you've described.   Your detailed explanation is incredibly helpful in guiding us to find the right solution.


Thanks again for your support!

**Comment by ling3ye** [comment]
Hi!   We've fixed some key mapping issues for German keyboards and just released a new version on the App Store (v1.8).

But, getting copy-paste to work reliably from host to target device has been more challenging than expected.   The current method involves reading from the host clipboard and simulating keypresses on the target.   This works okay for languages like German, but things get a lot trickier with languages like Japanese or Korean that require input method composition.

We're currently discussing how to best approach this and what it would take to support these more complex input systems.

If you have experience working with multilingual input or IMEs, we'd really appreciate your insights—or even better, come join the community discussion.   We'd love your help!

**Comment by ChibangLW** [comment]
@ling3ye it looks like this is still an issue. The app-internal keyboard-layout does not reflect the host keyboard layout, e.g. I have activated a systemwide German QWERTZ layout on macOS but the software keyboard is still QWERTY. 

<img width="1079" height="710" alt="Image" src="https://github.com/user-attachments/assets/16eed0c6-fd3b-45ea-9a8c-fedd3e6e683d" />

If I copy "QWERTZ" from the host and paste it to the target, I get "QWERTY".
If I type "QWERTZ" from the host, I get the correct "QWERTZ" on the target. 

Could you please revisit this issue?
